<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{73494d6d-a9c9-4353-aeaf-36b72084351a}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR

// Code also available on my GitHub (will make it public after the test closes)
// https://github.com/JPChurchouse/282762_PLCs/tree/main/Test
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//Q3(); // Uncomment to run Question Three
//Q4(); // Uncomment to run Question Four
//Q7(); // Uncomment to run Question Seven
Q6();
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="10" Count="0" />
      <LineId Id="9" Count="0" />
      <LineId Id="18" Count="0" />
      <LineId Id="17" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>