<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Q1" Id="{9b20c000-40aa-4785-aadb-ca6e9635d130}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Q1
VAR
	loop : INT := 1;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Q1">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>