<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Q2" Id="{697cbeb6-d739-4545-9ae0-31c7cee95e84}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Q2
VAR
	tempurature : REAL := 26.5;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Q2">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>